/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Interfaces.IPersona;
import Interfaces.IPersonaController;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import practica01cliente.RMI;

/**
 *
 * @author Yanglee DM
 */
public class PanelAgregarPersona extends javax.swing.JPanel {

   
    private JDialog dialogParent;
    
    public PanelAgregarPersona(JDialog dialogParent){
        initComponents();
        this.dialogParent = dialogParent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();

        nombreTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        telefonoTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        nombreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreLabel.setText("Ingresa el nombre");

        telefonoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefonoLabel.setText("Ingresa el teléfono");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText("Ingresa el email");

        aceptarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel)
                    .addComponent(telefonoLabel)
                    .addComponent(emailLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(emailTextField)
                    .addComponent(telefonoTextField))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(aceptarButton)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        try {
            String nombre = nombreTextField.getText();
            String telefono = telefonoTextField.getText();
            String email = emailTextField.getText();
            
            IPersona persona = RMI.getIPersonaController().newInstance();
            
            if (nombre.length() == 0 ){
                JOptionPane.showMessageDialog(
                        this, 
                        "Ingrese nombre",
                        "Validación",
                        JOptionPane.ERROR);
                nombreTextField.requestFocus();
                return;
            }else{
                persona.setNombre(nombre);
            } //Fin if-else
            if (telefono.length() > 0){
                persona.setTelefono(telefono);
            }
            if(email.length() == 0){
                JOptionPane.showMessageDialog(
                        this, 
                        "Ingrese email",
                        "Validación",
                        JOptionPane.ERROR);
                emailTextField.requestFocus();
                return;
            }else{
                persona.setEmail(email);
            }//Fin if-else
            
            int respuesta = RMI.getIPersonaController().add(persona);
            
            if(respuesta == IPersonaController.ADD_EXITO){
                JOptionPane.showMessageDialog(this,
                        "Persona añadida exitosamente",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
                dialogParent.dispose();
                
            }else if(respuesta == IPersonaController.ADD_SIN_EXITO){
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al añadir",
                        "Operación interrumpida",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_aceptarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
